from __future__ import annotations

from enum import IntEnum, StrEnum


class EvidenceLane(StrEnum):
    UNCLASSIFIED = "UNCLASSIFIED"
    SUPPORT = "SUPPORT"
    CONTRADICT = "CONTRADICT"
    RIVAL = "RIVAL"
    NULL = "NULL"
    BIAS_CRITIQUE = "BIAS_CRITIQUE"
    REPLICATION = "REPLICATION"
    CORRECTION_RETRACTION = "CORRECTION_RETRACTION"


class SourceStatus(StrEnum):
    VERIFIED = "VERIFIED"
    ASSERTED = "ASSERTED"
    UNVERIFIED = "UNVERIFIED"


class EpistemicStatus(StrEnum):
    OBSERVATION = "OBSERVATION"
    MEASUREMENT = "MEASUREMENT"
    ASSOCIATION = "ASSOCIATION"
    CAUSAL_INFERENCE = "CAUSAL_INFERENCE"
    INTERPRETATION = "INTERPRETATION"
    SIMULATION = "SIMULATION"
    RECOMMENDATION = "RECOMMENDATION"


class ClaimTier(StrEnum):
    DESCRIPTIVE_EVIDENCE_ONLY = "DESCRIPTIVE_EVIDENCE_ONLY"
    ASSOCIATION_ONLY = "ASSOCIATION_ONLY"
    LIMITED_CAUSAL_EVIDENCE = "LIMITED_CAUSAL_EVIDENCE"
    MODERATE_TRIANGULATED_CAUSAL_EVIDENCE = "MODERATE_TRIANGULATED_CAUSAL_EVIDENCE"
    HIGH_TRIANGULATED_CAUSAL_EVIDENCE = "HIGH_TRIANGULATED_CAUSAL_EVIDENCE"
    THEORY_DEPENDENT_INTERPRETATION = "THEORY_DEPENDENT_INTERPRETATION"
    SIMULATION_ONLY = "SIMULATION_ONLY"


class ModelFamily(StrEnum):
    INTRINSIC_RECOGNITION = "INTRINSIC_RECOGNITION"
    MULTIFACTORIAL_DEVELOPMENTAL_INSTITUTIONAL = (
        "MULTIFACTORIAL_DEVELOPMENTAL_INSTITUTIONAL"
    )
    ASCERTAINMENT_SERVICE = "ASCERTAINMENT_SERVICE"
    MIXTURE_HETEROGENEITY = "MIXTURE_HETEROGENEITY"
    NULL_OR_ALTERNATIVE = "NULL_OR_ALTERNATIVE"


class FindingDirection(StrEnum):
    SUPPORTS = "SUPPORTS"
    WEAKENS = "WEAKENS"
    FALSIFIES = "FALSIFIES"
    MIXED = "MIXED"
    NEUTRAL = "NEUTRAL"
    INCONCLUSIVE = "INCONCLUSIVE"


class FalsifierStatus(StrEnum):
    NOT_TESTED = "NOT_TESTED"
    NOT_TRIGGERED = "NOT_TRIGGERED"
    PARTIALLY_TRIGGERED = "PARTIALLY_TRIGGERED"
    TRIGGERED = "TRIGGERED"
    INCONCLUSIVE = "INCONCLUSIVE"


class AccessClass(StrEnum):
    OPEN = "OPEN"
    LICENSED = "LICENSED"
    PARTICIPANT_SECURE = "PARTICIPANT_SECURE"
    TRE_SDE = "TRE_SDE"


class AuthorityLevel(IntEnum):
    A6_RAW_HISTORY = 0
    A5_MODEL_PROPOSAL = 1
    A4_ACCEPTED_ANALYSIS_ARTEFACT = 2
    A3_VERIFIED_EVIDENCE_COMPUTATION = 3
    A2_HUMAN_GOVERNANCE_DECISION = 4
    A1_AUTHORISED_SPECIFICATION = 5
    A0_SYSTEM_CONSTITUTION = 6


class ContradictionClass(StrEnum):
    NOT_COMPARABLE = "NOT_COMPARABLE"
    SCOPE_MISMATCH = "SCOPE_MISMATCH"
    CONSTRUCT_MISMATCH = "CONSTRUCT_MISMATCH"
    PERIOD_MISMATCH = "PERIOD_MISMATCH"
    JURISDICTION_MISMATCH = "JURISDICTION_MISMATCH"
    ESTIMAND_MISMATCH = "ESTIMAND_MISMATCH"
    SUBSTANTIVE_CONTRADICTION = "SUBSTANTIVE_CONTRADICTION"
    CONSISTENT = "CONSISTENT"
